# This is a basic workflow to help you get started with Actions

name: Deploy to Salesforce Pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  workflow_call:
    secrets:
      SALESFORCECLIENTID:
        description: 'Client ID of org from connected app'
        required: true
      SALESFORCEURL:
        description: 'URL og org'
        required: true
      SALESFORCEUSERNAME:
        description: 'Username of org'
        required: true
 # commenting pull request for now not needed 
  # pull_request:
   # branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    environment: RegPack
    #env:
      #SALESFORCECLIENTID: ${{ secrets.SALESFORCECLIENTID }}
      #SALESFORCEURL: ${{ secrets.SALESFORCEURL }}
      #SALESFORCEUSERNAME: ${{ secrets.SALESFORCEUSERNAME }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Install PMD
    - name: 'Install PMD'
      run: |
          PMD_VERSION=`cat pmdRule/pmd-version.txt`
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F$PMD_VERSION/pmd-bin-$PMD_VERSION.zip
          unzip pmd-bin-$PMD_VERSION.zip -d ~
          mv ~/pmd-bin-$PMD_VERSION ~/pmd
          ~/pmd/bin/run.sh pmd --version
    # Artifacts directory     
    #- name: Create artifact files
     # run: |
        #mkdir -p path/to/dir-1/
    # Artifacts on failed PMD       
    #- name: Artifact
     # uses: actions/upload-artifact@v3
      #with:
       # name: 'Artifact-A'
        #path: path/to/dir-1/file1.txt
    - name: Step 1 - Create a temporary artifact downloads folder
      run: mkdir downloads
        
    - name: step 2 - Add artifacts to publish to the temp folder
      run: |
          cd downloads
          echo 'alpha'    > alpha.json
          echo 'testartifacts'    > testartifacts.txt
          cd ..
    # Artifacts on failed PMD       
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Artifact
        path: downloads
        
    # Validate - Apex - Code       
    - name: validate-apex-code
      #uses: legetz/setup-pmd@v6.48
      run: ~/pmd/bin/run.sh pmd -language apex --dir force-app/main/default/classes --rulesets pmdRule/apex_ruleset.xml -f text
      
    # Setup Node
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
          node-version: '18.x'
    
    # Install SFDX CLI
    - name: Install SFDX CLI
      #run: npm install sfdx-cli --global n latest
      run: npm install @salesforce/cli --global n latest
           sf version
    # Authorize SF Org
    - name: Authorize SF Org
      env:
        CLIENT_ID: ${{ secrets.SALESFORCECLIENTID }}
        USERNAME: ${{ secrets.SALESFORCEUSERNAME }}
        INSTANCE_URL: ${{ secrets.SALESFORCEURL }}
      run: sfdx force:auth:jwt:grant --client-id $CLIENT_ID --jwt-key-file ./buildfiles/server.key --username $USERNAME --instance-url $INSTANCE_URL -a regpack
      #run: sfdx auth:web:login --instance-url $INSTANCE_URL
           #sfdx force:org:open -u $USERNAME

    # Convert to Deploy Source
    #- name: Convert to Deploy Source
      #run: sfdx force:source:convert -r ./force-app -d ./toDeploy
    
    # Run Validation of Deploy Source
    - name: Run Validation on Deploy Source
      #run: sfdx force:mdapi:deploy -l RunLocalTests -c -d ./toDeploy -u prod -w 10
      run: sfdx force:source:deploy --checkonly --manifest manifest/package.xml -l RunLocalTests --target-org regpack --wait 120
    
    # Deploy
    - name : Deploy to SF Org
      #run: sfdx force:mdapi:deploy -l RunLocalTests -d ./toDeploy -u prod -w 10
      #when: manual
      run: sfdx force:source:deploy --manifest manifest/package.xml --target-org regpack
